---
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.int.home.lab`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - proxy
      - jenkins_net
  
  ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins-ssh
    networks:
      - jenkins_net

volumes:
  jenkins_home: 
    external: true

networks:
  jenkins_net:  
    external: true
  proxy:
    external: true